### ISSUE TITLE
Can the cronjob image be updated automatically by fluxcd?

### ISSUE THREAD

**Issue by somdoron** [hiddeco/cronjobber#32]
We're using fluxcd and cronjobber, we would like to automatically update the cronjob image.
Simple testing seems to show that currently, fluxcd cannot understand the cronjobber resource.

**Comment by somdoron** [comment]
@hiddeco I'm working on a pull request to fluxcd to support cronjobber.
Do you think such PR would be accepted?

**Comment by hiddeco** [comment]
@somdoron we do not accept the automation of new workload types for Flux at the moment, partly because this would open the door for support of other workloads, but mainly because Flux is not designed to support an endless amount of (non-native) resource kinds. We are currently working on GitOps Toolkit components that will result in a Flux v2, for which we plan to support the automation of custom resources (see: https://github.com/fluxcd/toolkit/discussions/107, and other [discussions](https://github.com/fluxcd/toolkit/discussions)).
